### ISSUE TITLE
Doesnt work in valorant?

### ISSUE THREAD

**Issue by Venadux** [dotdon/QuickSwitch#1]
Hey,
so I tried the script had the gui popup clicked the enable button and it said quickswitch mode enabled and it registered D and A key presses in the terminal but when I tried it out in valorant (the range) it did not seem to do anything when i held D and pressed A it just slowed me down but I kept going right. Perhaps im using it wrong? Idk just didnt work for me. anyways thank you for reading!

**Comment by dotdon** [comment]
Code has been fixed
