### ISSUE TITLE
Linux Support ?

### ISSUE THREAD

**Issue by Kyr4l** [dotdon/QuickSwitch#3]
The script requires `pywin32` which is a windows-only package, is there any alternative for Linux ?

**Comment by dotdon** [comment]
I updated the script to include Linux support must be run as root

**Comment by Kyr4l** [comment]
> I updated the script to include Linux support must be run as root

Is it the only possible solution ? No way to run it in user mode ?

**Comment by dotdon** [comment]
There is not a way to block the key switches at the user level that I know of.

**Comment by Kyr4l** [comment]
> There is not a way to block the key switches at the user level that I know of.

i have no idea either, that's why i'm asking x)

**Comment by dotdon** [comment]
I created a script using the X11 libraries to run this script without root privileges.
